<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Edi Wang</Authors>
		<Company>edi.wang</Company>
		<PackageTags>Password</PackageTags>
		<PackageProjectUrl>https://edi.wang</PackageProjectUrl>
		<RepositoryUrl>https://github.com/EdiWang/Edi.PasswordGenerator</RepositoryUrl>
		<Version>3.0.0</Version>
		<Description>Generate Chromium-style passwords with cryptographically secure randomness</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>edi-logo-blue.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\"/>
		<None Include="..\..\img\edi-logo-blue.png" Pack="true" PackagePath="\"/>
	</ItemGroup>
</Project>
